[package]
name = "qsv-stats"
version = "0.9.0"  #:version
authors = ["Joel Natividad <joel@dathere.com>"]
description = "Computing summary statistics on streams."
documentation = "https://docs.rs/qsv-stats"
homepage = "https://github.com/jqnatividad/rust-stats"
repository = "https://github.com/jqnatividad/rust-stats"
readme = "README.md"
keywords = ["statistics", "stats", "median", "mean", "stddev"]
categories = ["science", "math"]
license  = "MIT OR Unlicense"
edition = "2021"

[lib]
name = "stats"

[dependencies]
ahash = "0.8"
num-traits = "0.2"
rayon = "1.7"
serde = { version = "1.0", features = ["derive"] }
