[package]
name = "qsv-stats"
version = "0.3.3"  #:version
authors = ["Joel Natividad <joel@dathere.com>"]
description = "Experimental crate for computing basic statistics on streams."
documentation = "https://docs.rs/qsv-stats"
homepage = "https://github.com/jqnatividad/rust-stats"
repository = "https://github.com/jqnatividad/rust-stats"
readme = "README.md"
keywords = ["statistics", "stats", "median", "mean", "stddev"]
license = "Unlicense/MIT"

[lib]
name = "stats"

[dependencies]
num-traits = "0.2"
