[package]
name = "qsv-stats"
version = "0.3.7"  #:version
authors = ["Joel Natividad <joel@dathere.com>"]
description = "Experimental crate for computing basic statistics on streams."
documentation = "https://docs.rs/qsv-stats"
homepage = "https://github.com/jqnatividad/rust-stats"
repository = "https://github.com/jqnatividad/rust-stats"
readme = "README.md"
keywords = ["statistics", "stats", "median", "mean", "stddev"]
license  = "MIT OR Unlicense"
edition = "2021"

[lib]
name = "stats"

[dependencies]
ahash = "0.7.6"
num-traits = "0.2.14"
