[package]
name = "qsv-stats"
version = "0.5.1"  #:version
authors = ["Joel Natividad <joel@dathere.com>"]
description = "Computing descriptive statistics on streams."
documentation = "https://docs.rs/qsv-stats"
homepage = "https://github.com/jqnatividad/rust-stats"
repository = "https://github.com/jqnatividad/rust-stats"
readme = "README.md"
keywords = ["statistics", "stats", "median", "mean", "stddev"]
license  = "MIT OR Unlicense"
edition = "2021"
rust-version  = "1.66"

[lib]
name = "stats"

[dependencies]
ahash = "0.8"
num-traits = "0.2"
